hugobloem/stateful_scenes

custom_components/stateful_scenes/StatefulScenes.py
This pull request refactors the scene_conf icon retrieval to use the get() method instead of checking if the "icon" key exists in the scene_conf dictionary. This improves code readability and reduces the chance of a KeyError.
=> Refactor scene_conf icon retrieval to use get() method

README.md
This pull request adds download badges to the README file to display the total number of downloads and the latest release version. This provides users with more information about the popularity and availability of the project.
=> Add download badges to README

custom_components/stateful_scenes/StatefulScenes.py, custom_components/stateful_scenes/config_flow.py
This pull request removes the unused test_credentials method and adds tests for the code.
=> Remove unused test_credentials method and add tests

custom_components/stateful_scenes/StatefulScenes.py, custom_components/stateful_scenes/number.py, custom_components/stateful_scenes/switch.py
This pull request adds the `area_id` attribute to the scene configuration, allowing scenes to be associated with specific areas in Home Assistant.
=> Add area_id to scene configuration

custom_components/stateful_scenes/StatefulScenes.py
This pull request fixes the attribute access in the StatefulScenes.py file. Previously, the code was accessing the "id" attribute directly, which could result in an error if the attribute was not present. This PR updates the code to use the "get" method to safely access the attribute, providing a default value of None if the attribute is not found.
=> Fix attribute access in StatefulScenes.py

.gitignore, config/configuration.yaml, config/scenes.yaml, config/virtual.yaml, custom_components/stateful_scenes/StatefulScenes.py, custom_components/stateful_scenes/__init__.py, custom_components/stateful_scenes/config_flow.py
This pull request includes several fixes and improvements to the codebase:
- The transition time in the Scene class is now properly initialized to 0.0.
- The "hub" configuration in the discovery initialization is now set to False.
- Two new YAML files, virtual.yaml and scenes.yaml, have been added.
- The update_callback method now stores the old state instead of the current state.
- The initialization logic for stateful_scenes has been updated to handle the "hub" configuration correctly.
These changes address various issues and enhance the functionality of the software.
=> Various bug fixes

custom_components/stateful_scenes/StatefulScenes.py, custom_components/stateful_scenes/__init__.py, custom_components/stateful_scenes/switch.py
This pull request refactors the scene update callbacks to use the new event data format following the deprecation of `async_track_state_change`. The `update_callback` method now accepts an event object instead of individual parameters. Additionally, the `async_setup_entry` function has been updated to use `async_forward_entry_setups` instead of individually forwarding each platform.
=> refactor: scene update callbacks

custom_components/stateful_scenes/StatefulScenes.py, custom_components/stateful_scenes/switch.py
This pull request adds callback functions to the scene registration process. Previously, the callback functions were not being properly set, leading to errors when attempting to update a scene (see #97). With this change, the callback functions are properly set, ensuring that the scene registration process functions correctly.
=> fix: Add callback functions to scene registration

custom_components/stateful_scenes/switch.py
This pull request fixes the issue where the display switch was flashing instead of being displayed as a toggle. The `_attr_assumed_state` attribute has been changed from `True` to `False` in the `StatefulSceneSwitch` class.
=> fix: display switch as a toggle rather than flashes

custom_components/stateful_scenes/StatefulScenes.py
This pull request fixes the issue with incorrectly resolved areas. The `area_id` function is now replaced with `area_name` function to correctly retrieve the area name.
=> fix: areas incorrectly resolved

custom_components/stateful_scenes/StatefulScenes.py
This pull request fixes an issue where the scene restoration was triggered even when the scene was already turned off. The commit "fix(scene): do not restore if already off" ensures that the restoration is skipped if the scene is already off.
=> fix(scene): do not restore if already off

custom_components/stateful_scenes/manifest.json
This pull request includes a small change to the `custom_components/stateful_scenes/manifest.json` file. The change updates the documentation URL to point directly to the GitHub repository instead of the raw README file.
* [`custom_components/stateful_scenes/manifest.json`](diffhunk://#diff-dd23a4a92450f8aa8d142e0c68e0bcbb935fbc9931c1919c887d32315fb05fd5L8-R8): Updated the documentation URL to "https://github.com/hugobloem/stateful_scenes"
=> fix: correct documentation link

.github/workflows/lint.yaml
This pull request includes changes to the `.github/workflows/lint.yaml` file to update the setup process for the linting job. The most important changes involve switching from using Python to using UV, a different setup tool.
Updates to the linting job setup:
* [`.github/workflows/lint.yaml`](diffhunk://#diff-4b122024a3a28ded65da76a2f1bface1f3a27328374438d1298d25585fe0603bL20-R25): Changed from using `actions/setup-python@v5` to `astral-sh/setup-uv@v3` for setting up the environment.
* [`.github/workflows/lint.yaml`](diffhunk://#diff-4b122024a3a28ded65da76a2f1bface1f3a27328374438d1298d25585fe0603bL20-R25): Updated the version parameter from specifying `python-version: "3.11"` to `version: "latest"`.
* [`.github/workflows/lint.yaml`](diffhunk://#diff-4b122024a3a28ded65da76a2f1bface1f3a27328 …
=> ci: use uv in lint.yaml

custom_components/stateful_scenes/switch.py
Reflect actual state of the scene whenever Home Assistant restarts. Fixes https://github.com/hugobloem/stateful_scenes/issues/146
=> fix: Actual Scene State on Restart

custom_components/stateful_scenes/StatefulScenes.py
The current behavior is to compare all attributes regardless if the device is off which fails a match for devices that are off when individual attributes change.  For example  a scene that, by definition, turns off all of its devices will not be considered on/active if any individual attribute is different than the defined scene entity state.
If a scene includes entities that have a defined off state those entities should be considered off regardless of their other attributes in the off state.  For example a thermostat temperature may be changed from the original scene definition but the thermostat is still off, etc.  A light's color may be blue instead of red but the light is still off.  It is common for attributes like brightness to vary when a device is off but off is the overriding …
=> fix: If the scene 'on' state includes entities that are off don't check additional attributes

README.md, custom_components/stateful_scenes/StatefulScenes.py, custom_components/stateful_scenes/select.py, custom_components/stateful_scenes/switch.py
Fixes issuse #166 race condition
This pull request does a few things to address the race condition:
- Moves the handling of debounce time to the device level (stateful scene) instead of per entity
- Substitutes HA scheduling routines for the use of sleep
- Combines the transition time to the debounce time in such a way that the transition occurs and then debounce is added as a delay before evaluation of the scene
The UI switch remains responsive so the user can turn the scene on/off at will.  When the user changes the stateful scene during a period where the transition or debounce is in play the scene changes state as would be expected and resets any pending delay in evaluation.
If an external source changes one of the entities that the scene controls during the transition/debounce the …
=> fix: address race condition and consider transition time when using debounce

custom_components/stateful_scenes/StatefulScenes.py, custom_components/stateful_scenes/__init__.py, custom_components/stateful_scenes/discovery.py, custom_components/stateful_scenes/number.py, custom_components/stateful_scenes/select.py, custom_components/stateful_scenes/switch.py
Eliminate unnecessary calls to asyncio.run_coroutine_threadsafe due to sync methods calling async routines for eval with the eval timer.  The entire integration is now async.
The switch now relies on the Scene to fully initialize in the scene's init solving a race condition where the switch was trying to get the scene to update its state / eval while it may not be initialized.  The switch now relies solely on the scene is_on so it is always in sync with the scene.
Addresses issue #170 and #174.  Apologies for the sweeping change but async is really necessary given the interactions with switch, debounce.
=> fix: Modify the integration to fully use HA async paradigm.

custom_components/stateful_scenes/StatefulScenes.py
Simplify the initialization of states and restore states using `dict.fromkeys` for improved readability and efficiency.
=> refactor: simplify state initialization using dict.fromkeys

custom_components/stateful_scenes/select.py
Refactor methods in StatefulSceneOffSelect to use asynchronous calls, improving performance and responsiveness.
=> fix: convert synchronous methods to asynchronous in StatefulSceneOffSelect

custom_components/stateful_scenes/__init__.py, custom_components/stateful_scenes/helpers.py, scripts/develop
Adds automatic cleanup of orphaned stateful scene entities and devices that no longer have corresponding scenes in the configuration. Previously, removing scenes from `scenes.yaml` would leave behind orphaned entities and devices that were not cleaned up.
Fixes #202
=> fix: cleanup orphaned entities and devices when scenes are removed
